version: "3"

volumes:
  redis-data:

services:
  redis:
    image: redis:alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "Jn4haJxjuEDIO"]
    restart: unless-stopped
    volumes:
      - redis-data:/data:Z
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports: 
      - "6379:6379"