version: "3.7"

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-1-replica-data:
  redis-node-2-replica-data:
  redis-node-3-replica-data:

networks:
  redis-net:
    driver: bridge

services:
  redis-node-1:
    image: redis:latest
    container_name: redis-node-1
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-node-1-data:/data
    ports:
      - "6379:6379"
    networks:
      - redis-net

  redis-node-2:
    image: redis:latest
    container_name: redis-node-2
    command: redis-server --port 6380 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-node-2-data:/data
    ports:
      - "6380:6380"
    networks:
      - redis-net

  redis-node-3:
    image: redis:latest
    container_name: redis-node-3
    command: redis-server --port 6381 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-node-3-data:/data
    ports:
      - "6381:6381"
    networks:
      - redis-net

  redis-node-1-replica:
    image: redis:latest
    container_name: redis-node-1-replica
    command: redis-server --port 6382 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-replica-no-failover yes
    volumes:
      - redis-node-1-replica-data:/data
    ports:
      - "6382:6382"
    networks:
      - redis-net

  redis-node-2-replica:
    image: redis:latest
    container_name: redis-node-2-replica
    command: redis-server --port 6383 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-replica-no-failover yes
    volumes:
      - redis-node-2-replica-data:/data
    ports:
      - "6383:6383"
    networks:
      - redis-net

  redis-node-3-replica:
    image: redis:latest
    container_name: redis-node-3-replica
    command: redis-server --port 6384 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-replica-no-failover yes
    volumes:
      - redis-node-3-replica-data:/data
    ports:
      - "6384:6384"
    networks:
      - redis-net

  # One time setup, use instead sentinels for continuous monitoring
  redis-cluster-setup:
    image: redis:latest
    container_name: redis-cluster-setup
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    volumes:
      - ./redis-cluster-setup.sh:/redis-cluster-setup.sh
    networks:
      - redis-net
    command: sh /redis-cluster-setup.sh
