version: "3.9"

volumes:
  redis-node-1-data:
  redis-node-1-replica-data:

networks:
  redis-net:
    driver: bridge

services:
  redis-node-1:
    image: redis:latest
    container_name: redis-node-1
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-node-1-data:/data
    ports:
      - "6379:6379"
    networks:
      - redis-net

  redis-node-1-replica:
    image: redis:latest
    container_name: redis-node-1-replica
    command: redis-server --port 6382 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-replica-no-failover yes
    volumes:
      - redis-node-1-replica-data:/data
    ports:
      - "6382:6382"
    networks:
      - redis-net

  # One time setup, use instead sentinels for continuous monitoring
  redis-cluster-setup:
    image: redis:latest
    container_name: redis-cluster-setup
    depends_on:
      - redis-node-1
    volumes:
      - ./redis-cluster-setup.sh:/redis-cluster-setup.sh
    networks:
      - redis-net
    command: sh /redis-cluster-setup.sh
