version: '3.9'

volumes:
  master-data:
  slave-1-data:
  slave-2-data:
  trainingdata:
  pgadmindata:

services:
  master:
    image: redis:latest
    container_name: redis-master
    volumes:
      - master-data:/data
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"  

  slave-1:
    image: redis:latest
    container_name: redis-slave-1
    command: redis-server --slaveof redis-master 6379 --appendonly yes
    volumes:
      - slave-1-data:/data
    ports:
      - "6380:6379" 
    depends_on:
    - master

  slave-2:
    image: redis:latest
    container_name: redis-slave-2
    command: redis-server --slaveof redis-master 6379 --appendonly yes
    volumes:
      - slave-1-data:/data
    ports:
      - "6381:6379" 
    depends_on:
    - master
    

  sentinel-1:
    build:
      context: ./sentinel
      dockerfile: Dockerfile
    container_name: redis-sentinel-1
    environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000
    depends_on:
    - master
    - slave-1
    - slave-2

  sentinel-2:
    build:
      context: ./sentinel
      dockerfile: Dockerfile
    container_name: redis-sentinel-2
    environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000
    depends_on:
    - master
    - slave-1
    - slave-2

  sentinel-3:
    build:
      context: ./sentinel
      dockerfile: Dockerfile
    container_name: redis-sentinel-3
    environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000
    depends_on:
    - master
    - slave-1
    - slave-2

  training-postgres:
    image: postgres:alpine
    container_name: training-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=training
      - POSTGRES_PASSWORD=training
      - POSTGRES_DB=training
    ports:
      - 5432:5432
    volumes:
      - trainingdata:/var/lib/postgresql/data:Z

  training-admin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=redis.training@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=training
    volumes:
      - pgadmindata:/var/lib/pgadmin4/storage
